stages:
  - install
  - lint
  - test
  - build
  - deploy

image: node:22

install:
  stage: install
  script:
    - cd my-app
    - npm ci

lint:
  stage: lint
  script:
    - cd my-app
    - npm run lint

test:
  stage: test
  script:
    - cd my-app
    - npm test -- --watchAll=false

build:
  stage: build
  script:
    - cd my-app
    - CI=false npm run build

trigger-deploy:
  stage: deploy

  trigger:
    project: 1dv613/student/sa226jf/workspace/lifeFlow-deploy
    branch: main
