default:
  artifacts:
    expire_in: 1 day

stages:
  - install
  - lint
  - test
  - build
  - deploy

image: node:22-alpine

cache:
  key:
    files:
      - app/package-lock.json
  paths:
    - app/.npm/

install:
  stage: install

  script:
    - cd app
    - npm ci --cache .npm --prefer-offline

  artifacts:
    paths:
      - app/node_modules/

lint:
  stage: lint

  dependencies:
    - install

  script:
    - cd app
    - npm run lint

test:
  stage: test

  dependencies:
    - install

  script:
    - cd app
    - CI=false npm test -- --watchAll=false

build:
  stage: build

  dependencies:
    - install

  script:
    - cd app
    - CI=false npm run build

build-image:
  stage: build

  image:
    name: gcr.io/kaniko-project/executor:v1.23.1-debug
    entrypoint: [""]

  script:
    - mkdir -p /kaniko/.docker

    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/app"
      --dockerfile "${CI_PROJECT_DIR}/app/Dockerfile"
      --cache=true
      --destination "${CI_REGISTRY_IMAGE}:latest"

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

trigger-deploy:
  stage: deploy

  needs:
    - lint
    - test
    - build
    - build-image

  trigger:
    project: 1dv613/student/sa226jf/workspace/lifeflow-deploy
    branch: main
    strategy: depend

  variables:
    IMAGE_TAG: $CI_COMMIT_SHA

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
