server {
    listen 80;
    server_name cu0039.camp.lnu.se;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://backend:5000/;
    }
}
